/**
 * 登录环境快照（慢 profile 主机的终端 / 会话 shell 加速）。
 *
 * 背景：Atlas/ModelArts 这类训练机的登录 profile 常有重量级步骤（实测一台
 * 机器 `source /usr/local/Ascend/nnal/atb/set_env.sh` 单次 24~77 秒——每次
 * import torch_npu 收集 CANN 环境）。侧栏终端（登录 shell）与会话常驻
 * shell（`bash -l`）首开都要付这笔钱。
 *
 * 方案（对每台主机自动做一次，之后毫秒级启动）：
 *  1. 捕获：后台跑一次 `bash -lc 'export -p; declare -f; alias; PS1'`，
 *     过滤会话级易变变量，拼成可 source 的快照脚本写到远端
 *     ~/.cache/dsh-cloud-workspaces/login-env.sh（engine.writeFile）；
 *  2. 重放：终端/会话 shell 改开非登录 shell（bash --noprofile --norc），
 *     引导命令先 `[ -f 快照 ] && . 快照` —— 环境（变量/函数/alias/PS1）
 *     与登录 shell 等价，但跳过 profile 执行本身；
 *  3. 兜底：快照缺失 → 原登录 shell 路径，不会更糟。
 *
 * 本模块只做纯文本处理（命令串/解析/组装），IO 全在 engine。
 */

/** 捕获命令（bash -lc 保证走完整登录 profile；标记分段便于忽略 profile 自身噪声）。 */
export const LOGIN_ENV_CAPTURE_COMMAND = [
  'bash -lc \'printf "__DSH_ENV_BEGIN__\\n"',
  'export -p',
  'printf "\\n__DSH_ENV_FUNCS__\\n"',
  'declare -f',
  'printf "\\n__DSH_ENV_ALIASES__\\n"',
  'alias',
  'printf "__DSH_ENV_PS1__%s\\n" "$PS1"\'',
].join('; ')

/** 快照在远端的固定路径（相对 $HOME）。 */
export const LOGIN_ENV_RELATIVE_PATH = '.cache/dsh-cloud-workspaces/login-env.sh'

/** 快照远端绝对路径。 */
export function loginEnvRemotePath(home: string): string {
  const base = home.endsWith('/') ? home.slice(0, -1) : home
  return `${base}/${LOGIN_ENV_RELATIVE_PATH}`
}

/**
 * 不得进快照的变量：会话特定（SSH/TTY/显示）或 shell 每次自变的伪变量。
 * 重放它们要么失效（路径不属于新会话），要么污染终端（TERM/COLUMNS）。
 */
const VOLATILE_ENV_NAMES = new Set([
  '_', 'SHLVL', 'PWD', 'OLDPWD', 'TERM', 'TERM_PROGRAM', 'COLUMNS', 'LINES',
  'SSH_CLIENT', 'SSH_TTY', 'SSH_CONNECTION', 'SSH_AUTH_SOCK', 'SSH_AGENT_PID',
  'DISPLAY', 'WAYLAND_DISPLAY', 'XDG_SESSION_ID', 'XDG_SESSION_CLASS', 'XDG_SESSION_TYPE',
  'EPOCHREALTIME', 'EPOCHSECONDS', 'RANDOM', 'SECONDS', 'LINENO', 'HISTCMD', 'MAIL',
  'BASH_ARGV', 'BASH_ARGC', 'BASH_SOURCE', 'BASH_LINENO', 'BASH_VERSINFO',
  'BASH_SUBSHELL', 'BASH_EXECUTION_STRING', 'BASH_CMDS', 'BASH_XTRACEFD',
  'DIRSTACK', 'GROUPS', 'PIPESTATUS', 'FUNCNAME', 'MC_SID', 'MC_TMPDIR',
])

function isVolatileEnvName(name: string): boolean {
  return VOLATILE_ENV_NAMES.has(name) || name.startsWith('SSH_')
}

/** export -p 输出行（declare -x NAME=... / export NAME=...）→ 变量名；非导出行 → null。 */
function exportNameOf(line: string): string | null {
  const match = /^(?:declare -x |export )([A-Za-z_][A-Za-z0-9_]*)=/.exec(line)
  return match === null ? null : match[1]
}

/** POSIX 单引号包裹（值内单引号转义为 '\''）。 */
function posixSingleQuote(value: string): string {
  return `'${value.replace(/'/g, "'\\''")}'`
}

/** 组装产物：可直接写入远端的脚本 + 统计。 */
export interface AssembledLoginEnv {
  script: string
  varCount: number
}

/**
 * 捕获输出 → 快照脚本。profile 自身的 stdout（如欢迎横幅）出现在
 * __DSH_ENV_BEGIN__ 之前，解析按标记分段天然忽略。标记缺失/空环境 →
 * undefined（调用方按捕获失败处理，回退登录 shell）。
 */
export function assembleLoginEnvScript(stdout: string): AssembledLoginEnv | undefined {
  const beginMarker = '__DSH_ENV_BEGIN__'
  const funcsMarker = '__DSH_ENV_FUNCS__'
  const aliasesMarker = '__DSH_ENV_ALIASES__'
  const ps1Marker = '__DSH_ENV_PS1__'
  const begin = stdout.indexOf(beginMarker)
  if (begin === -1) return undefined
  const afterBegin = stdout.indexOf('\n', begin) + 1
  const funcsAt = stdout.indexOf(funcsMarker, afterBegin)
  const aliasesAt = stdout.indexOf(aliasesMarker, funcsAt === -1 ? afterBegin : funcsAt)
  const ps1At = stdout.indexOf(ps1Marker, aliasesAt === -1 ? afterBegin : aliasesAt)
  if (funcsAt === -1 || aliasesAt === -1 || ps1At === -1) return undefined
  const section = (from: number, to: number): string => {
    const body = stdout.slice(stdout.indexOf('\n', from) + 1, to)
    return body.endsWith('\n') ? body.slice(0, -1) : body
  }
  const exportsText = stdout.slice(afterBegin, funcsAt)
  const funcsText = section(funcsAt, aliasesAt)
  const aliasesText = section(aliasesAt, ps1At)
  const ps1Tail = stdout.slice(ps1At + ps1Marker.length)
  const ps1 = ps1Tail.slice(0, ps1Tail.indexOf('\n') === -1 ? undefined : ps1Tail.indexOf('\n'))

  const exportLines = exportsText
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => {
      if (line === '') return false
      const name = exportNameOf(line)
      return name !== null && !isVolatileEnvName(name)
    })
  if (exportLines.length === 0) return undefined

  const parts: string[] = [
    '# Generated by dsh-cloud-workspaces — login environment snapshot.',
    '# Sourced by fast-start terminals/shells instead of running the login profile.',
    '# To refresh: Settings → SSH 连接 → 预热终端环境 (or re-run capture).',
    '',
    ...exportLines,
  ]
  if (funcsText.trim() !== '') {
    parts.push('', '# --- shell functions (declare -f) ---', funcsText)
  }
  if (aliasesText.trim() !== '') {
    parts.push('', '# --- aliases ---', aliasesText)
  }
  if (ps1.trim() !== '') {
    parts.push('', 'export PS1=' + posixSingleQuote(ps1))
  }
  return { script: parts.join('\n') + '\n', varCount: exportLines.length }
}
